compiler : 
 - clang++-3.6
 - clang++-3.7
language : cpp
script : make test

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
	- h-rayflood/llvm
    packages:
    - clang++-3.6
    - clang++-3.7