compiler : 
 - clang++-3.6
 - clang++-3.7
language : cpp
script : make test

install:
  - sudo add-apt-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main'
  - sudo add-apt-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.7 main'
  - sudo apt-get update -qq
  - sudo apt-get install --allow-unauthenticated $COMPILER