compiler : 
 - clang++-3.6
 - clang++-3.7
language : cpp
script : make test FLAGS+=-stdlib=libstdc++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - llvm-toolchain-precise-3.7
    packages:
    - libstdc++-4.9-dev
    - clang-3.6
    - clang-3.7